import { pgTable, serial, text, timestamp } from "drizzle-orm/pg-core";

/**
 * Database schema barrel (single source of truth for persistence shapes).
 *
 * - `auth-schema.ts` — Better Auth's tables (user, session, account,
 *   verification). Generated by the official Better Auth CLI from the real auth
 *   configuration; do not hand-edit.
 * - `rune-space.ts` — RuneSpace ownership and authoritative gameplay state.
 * - `schemaMeta` — trivial health-check table from the foundation scaffold.
 *
 * `db/index.ts` imports `* as schema` from here so the Drizzle instance and
 * migrations share one definition.
 */

export * from "./auth-schema";
export * from "./rune-space";

export const schemaMeta = pgTable("schema_meta", {
  id: serial("id").primaryKey(),
  key: text("key").notNull().unique(),
  value: text("value").notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export type SchemaMeta = typeof schemaMeta.$inferSelect;
export type NewSchemaMeta = typeof schemaMeta.$inferInsert;
